### ISSUE TITLE
Nice work! But It misses some binaries.

### ISSUE THREAD

**Issue by maniac-en** [holmes-py/Staticbinscraper#1]
##### Hey, after I saw your script, I felt that it's probably missing some binaries, So I went ahead and wrote a `bash` command, and indeed, your script does miss some binaries. Please check and confirm! Thanks 💯 
```
- Actual binaries: 392
- Downloaded binaries from the script: 346
```
##### `command`
```sh
mkdir bins && cd bins; \
	wget -r -e robots=off -nH --cut-dirs=3 --no-parent --accept-regex='busybox_' -R html,tmp,txt https://busybox.net/downloads/binaries/1.31.0-i686-uclibc/ ; \
	rename 's/busybox_//;y/A-Z/a-z/' *; chmod +x *
```

**Comment by holmes-py** [comment]
Cross-checked it, apparently I messed up with the regex about numbers in binary names. 
Will update the regex, thanks for that!
